# Generated by Django 5.0.7 on 2024-09-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackendBil", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cid",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="employee_id",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
