# Generated by Django 5.0.7 on 2024-08-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackendBil", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankstatement",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
