# Generated by Django 5.0.7 on 2024-09-11 07:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BackendBil", "0002_alter_user_cid_alter_user_employee_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankstatement",
            name="user",
        ),
        migrations.RemoveField(
            model_name="dailyreportbankstatement",
            name="user",
        ),
    ]
